# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

#resolver: ghc-7.8.4
resolver: lts-2.2.0

packages:
- .

extra-deps: [ConfigFile-1.1.4]
# flags: {}
# extra-package-dbs: []

system-ghc: true
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
