# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

#resolver: ghc-8.10.7
resolver: lts-18.10

packages:
- 'common'
- 'app'

# extra-deps: [ConfigFile-1.1.4, dequeue-0.1.12]
# flags: {}
# extra-package-dbs: []

system-ghc: true
install-ghc: false
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
